---
- name: Installation de MariaDB et Symfony 6
  hosts: all
  become: yes

  vars:
    db_user: my_user
    db_password: my_password
    db_name: my_database

  tasks:
    - name: Mettre à jour les dépendances
      become: yes
      apt:
        update_cache: yes

    - name: Installation de MariaDB
      apt:
        name: ['mariadb-server', 'python3-pymysql']
        state: present

    - name: Configuration de MariaDB
      template:
        src: templates/my.cnf.j2
        dest: /etc/mysql/my.cnf
        owner: root
        group: root
        mode: 0644
      notify:
        - restart mysql

    - name: Redémarrage de MariaDB
      service:
        name: mysql
        state: restarted

    #- name: Changer le mot de passe de root
    #  ansible.builtin.command:
    #    cmd: mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'test';"
    #    warn: no

    #- name: Création d'un utilisateur et d'une base de données MariaDB
    #  mysql_user:
    #    name: "{{ db_user }}"
    #    password: "{{ db_password }}"
    #    login_user: root
    #    login_password: "test"
    #    priv: "{{ db_name }}.*:ALL"
    #    state: present
    #  notify:
    #    - restart mysql

    - name: Ajouter le PPA ondrej/php
      apt_repository:
        repo: ppa:ondrej/php
        update_cache: yes

    - name: Installer PHP 8.2
      apt:
        name: php8.2
        state: present
        update_cache: yes

    - name: Installer les extensions PHP requises
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - php8.2-cli
        - php8.2-curl
        - php8.2-gd
        - php8.2-intl
        - php8.2-mbstring
        - php8.2-mysql
        - php8.2-soap
        - php8.2-xml
        - php8.2-zip

    - name: Installation de Composer
      apt:
        name: composer
        state: present

    - name: Créer le répertoire e-commerce
      become: yes
      file:
        path: /var/www/e-commerce
        state: directory
        mode: '0755'

    - name: Clonage de l'application Symfony 6
      unarchive:
        src: files/archive.zip
        dest: /var/www/e-commerce

    - name: Installation des dépendances de Symfony
      composer:
        command: install
        working_dir: /var/www/e-commerce
        no_dev: yes

    - name: Configuration de l'application Symfony
      template:
        src: templates/parameters.yml.j2
        dest: /var/www/e-commerce/app/config/parameters.yml
        owner: www-data
        group: www-data
        mode: 0644

    - name: Vérification de la configuration de Symfony
      command: php /var/www/e-commerce/bin/console doctrine:schema:validate --no-interaction
      ignore_errors: yes
      register: schema_validate

    - name: Mise à jour du schéma de la base de données
      command: php /var/www/e-commerce/bin/console doctrine:schema:update --force --no-interaction
      when: schema_validate.stderr.find('no matching mapping found') != -1
      become: yes

  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
